## **NPS (Net Promoter Score)**

As a Data Analyst at **Airbnb**, the task involves analyzing user survey data and reporting the ***Net Promoter Score (NPS)*** to the manager. NPS measures customer satisfaction and the likelihood of customers recommending the service to others.

Customers are asked to rate their likelihood to recommend the service on a scale from **0 to 10**:

* **0–6** → **Detractors** (unlikely to recommend, possibly speaking negatively)

* **7–8** → **Neutrals / Passives** (satisfied but not enthusiastic enough to actively recommend)

* **9–10** → **Promoters** (loyal enthusiasts who are highly likely to recommend)

Load the dataset to the Colab Notebook

In [1]:
!gdown 1clqWsIFkVaR5w0bKkOk5aYqiVhpAtsBY

Downloading...
From: https://drive.google.com/uc?id=1clqWsIFkVaR5w0bKkOk5aYqiVhpAtsBY
To: /content/NPS Score.txt
100% 2.55k/2.55k [00:00<00:00, 7.43MB/s]


In [2]:
# Import required library
import numpy as np

In [3]:
# load data
scores = np.loadtxt('NPS Score.txt', dtype = 'int')
scores

array([ 7, 10,  5, ...,  5,  9, 10])

In [4]:
# detail of the data
scores.ndim

1

In [5]:
scores.shape

(1167,)

### Analysis on the 1 dimensional Array

In [6]:
#print first 10 users ratings
scores[:10]

array([ 7, 10,  5,  9,  9,  4,  7,  9,  9,  9])

Use NumPy technique is used to filter scores where respondents are **detractors (score ≤ 6)**?

In [7]:
detractor = scores[scores <= 6]
detractor

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

In [14]:
len(detractor)

332

Filter who exactly are detractors

In [25]:
scores<=6

array([False, False,  True, ...,  True, False, False])

### **Identify Problems from Detractor Feedback**

Array has Boolean values and True are detractors , If you have metadata (age group, purchase type, location), group ratings by these to see patterns.


Along with this info , you can identify who exactly are detractors , find out their name , contact details and reviews on it and many more.

Calculate neutral percentage where the scores are 7 or 8

In [22]:
neutral = scores[(scores>=7) & (scores<=8)]
len(neutral)

226

In [23]:
neutral_percentage = len(neutral)/len(scores) * 100
neutral_percentage

19.365895458440445

### **Ways to turn Neutral into Promoters**
Create strategies:

* Look at historical changes in NPS to see if initiatives helped move people upward.

* If possible, run correlation with other business metrics to find improvement areas.

Calculates the percentage of Promoters (where score >= 9) from the NumPy array score?

In [9]:
promoters = scores[scores >= 9]
promoters[:10]

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10])

In [12]:
len(promoters) # how many promoters are there

609

In [15]:
#Alternate of finding out how many promoters are there
sum(scores >= 9)

np.int64(609)

In [18]:
percentage_promoters = len(promoters)/len(scores) * 100
print(np.round(percentage_promoters, 2))

52.19


Calculate NPS Score = %Promoters - %Detractors

In [21]:
nps_score = (len(promoters) - len(detractor)) / len(scores) * 100
print(np.round(nps_score, 2))

23.74
